import { defineConfig } from "vite";
import { resolve } from "path";

import dts from "vite-plugin-dts";

export default defineConfig({
  build: {
    outDir: "./dist",
    minify: false,
    lib: {
      entry: [
        "./src/index.ts",
        "./src/kv/index.ts",
      ],
      formats: ["es"],
    },
    rollupOptions: {
      plugins: [
        // NOTE: Needs to be in `rollupOptions` rather than vite's plugins to apply to each input.
        dts({
          rollupTypes: true,
          // NOTE: Inlucde .d.ts files generated by `jco`.
          copyDtsFiles: true,
          // NOTE: The .d.ts files generated by `jco` contain dynamic imports.
          staticImport: true,
        }),
      ],
      input: {
        "index": resolve(__dirname, 'src/index.ts'),
        "kv": resolve(__dirname, 'src/kv/index.ts'),
      },
      output: {
        entryFileNames: "[name].js",
      },
      external: (source) => {
        return source.startsWith("wasi:") || source.startsWith("trailbase:");
      },
    },
  },
});
