import { defineConfig } from "vite";

import dts from "vite-plugin-dts";

export default defineConfig({
  plugins: [
    dts({
      rollupTypes: true,
      // NOTE: Inlucde .d.ts files generated by `jco`.
      copyDtsFiles: true,
      // NOTE: The .d.ts files generated by `jco` contain dynamic imports.
      staticImport: true,
    }),
  ],
  build: {
    outDir: "./dist",
    minify: false,
    lib: {
      entry: "./src/index.ts",
      name: "runtime",
      fileName: "index",
      formats: ["es"],
    },
    rollupOptions: {
      external: (source) => {
        return source.startsWith("wasi:") || source.startsWith("trailbase:");
      },
      output: {
        inlineDynamicImports: true,
      },
    },
  },
});
