# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config_api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import config_pb2 as config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63onfig_api.proto\x12\x06\x63onfig\x1a\x0c\x63onfig.proto\"A\n\x11GetConfigResponse\x12\x1e\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x0e.config.Config\x12\x0c\n\x04hash\x18\x02 \x01(\t\"C\n\x13UpdateConfigRequest\x12\x1e\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x0e.config.Config\x12\x0c\n\x04hash\x18\x02 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETCONFIGRESPONSE._serialized_start=42
  _GETCONFIGRESPONSE._serialized_end=107
  _UPDATECONFIGREQUEST._serialized_start=109
  _UPDATECONFIGREQUEST._serialized_end=176
# @@protoc_insertion_point(module_scope)
