// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthUiSettings = {
  title?: string;
  icon_url?: string;
  /**
   * E.g. mailto://test@trailbase.io.
   */
  contact_url?: string;
  /**
   * Typically a page detailing the terms.
   */
  terms_url?: string;
  /**
   * Typically a page detailing PII usage.
   */
  privacy_url?: string;
  /**
   * Typically a page declaring a legal entity for ownership and/or authorship.
   */
  impressum_url?: string;
};
