packages:
  - 'client/testfixture/guests/typescript'
  - 'crates/assets/js/admin'
  - 'crates/assets/js/client'
  - 'crates/auth-ui/ui'
  - 'docs'
  - 'docs/examples/record_api_ts'
  - 'docs/examples/wasm-guest-ts'
  - 'examples/blog/web'
  - 'examples/coffee-vector-search'
  - 'examples/coffee-vector-search/guests/typescript'
  - 'examples/collab-clicker-ssr'
  - 'examples/collab-clicker-ssr/guests/typescript'
  - 'examples/data-cli-tutorial'
  - 'examples/tanstack-db-sync'
  - 'examples/wasm-guest-js'
  - 'examples/wasm-guest-ts'
  - 'guests/typescript'
allowBuilds:
  '@scarf/scarf': true
  '@tree-sitter-grammars/tree-sitter-yaml': true
  core-js-pure: true
  esbuild: true
  protobufjs: true
  sharp: true
  tree-sitter: true
  tree-sitter-json: true
minimumReleaseAgeExclude:
  - trailbase@0.13.1
overrides:
  form-data@>=4.0.0 <4.0.6: ^4.0.6
audit:
  ignore:
    - GHSA-mp2f-45pm-3cg9 # decompress: package is unmaintained
    - GHSA-hrh2-vp3x-79xf # decompress: package is unmaintained
    - GHSA-h39j-r5qq-r9mm # decompress: package is unmaintained
    - GHSA-jwp9-9v96-94mx # decompress: package is unmaintained
    - GHSA-528h-pc64-c93x # stream-json: update requires major version bump
    - GHSA-8cw4-87c7-c6xx # csv-parse: update requires major version bump
