name: "Release Component"
description: "Builds and packages a WASM component"

# RUST_TARGET: wasm32-wasip2
# BINARY_PATH: target/$RUST_TARGET/release/trailbase_auth_ui_component.wasm
# ARCHIVE_NAME: trailbase_${{  github.ref_name }}_wasm_auth_ui.zip

inputs:
  rust-target:
    required: false
  toolchain-version:
    required: true
  binary-path:
    required: true
  package-name:
    description: "Cargo package name"
    required: true
  archive-name:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update && \
          sudo apt-get install -y --no-install-recommends curl libssl-dev pkg-config libclang-dev protobuf-compiler libprotobuf-dev zip

    - uses: ./.github/actions/setup_pnpm

    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain-version }}
        target: ${{ inputs.rust-target }}

    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: release-wasm-${{ inputs.package-name }}

    - name: Rust Build
      shell: bash
      run: |
        env && cargo build -p ${{ inputs.package-name }} --target ${{ inputs.rust-target }} --release

    - name: Package Artifacts
      shell: bash
      run: |
        zip -r -j ${{ inputs.archive-name }} ${{ inputs.binary-path }} CHANGELOG.md LICENSE
