[package]
name = "trailbase-wasm-runtime-axum"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
axum = { workspace = true }
bytes = { workspace = true }
cron = { workspace = true }
form_urlencoded = "1.2.2"
futures-util = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
log = { workspace = true }
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true }
trailbase-sqlite = { workspace = true }
trailbase-wasm-common = { workspace = true }
trailbase-wasm-runtime-host = { workspace = true }
url = "2.5.8"
utoipa-axum = { workspace = true }

[dev-dependencies]
clap = { workspace = true }
env_logger = { workspace = true }
