[package]
name = "trailbase-sqlite"
version = "0.3.0"
edition = "2024"
license = "OSL-3.0"
description = "Async SQLite connection for TrailBase"
homepage = "https://trailbase.io"
repository = "https://github.com/trailbaseio/trailbase"
readme = "../../README.md"
autobenches = false

[[bench]]
name = "synthetic"
path = "benches/synthetic/benchmark.rs"
harness = false

[[bench]]
name = "join-order"
path = "benches/join-order/main.rs"
harness = false

[features]
default = []
generic = ["pg"]
pg = ["dep:postgres", "dep:bytes", "dep:trailbase-pgrow2serde", "dep:regex", "dep:sqlparser"]

[dependencies]
bytes = { workspace = true, optional = true }
crossfire = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
postgres = { version = "0.19.14", optional = true, features = ["with-serde_json-1"] }
regex = { version = "1.13.1", optional = true}
rusqlite = { workspace = true }
self_cell = "1.3.0"
serde = { workspace = true }
serde_json = { workspace = true }
serde_rusqlite = { workspace = true }
smallvec = { version = "1.16.0", features = ["const_generics"] }
sqlparser = { version = "0.62.0", optional = true }
thiserror = "2.0.20"
tokio = { workspace = true }
trailbase-pgrow2serde = { workspace = true, optional = true }

[dev-dependencies]
chrono = { workspace = true }
criterion = { version = "0.8", features = ["html_reports", "async_tokio"] }
csv = "1.4.0"
env_logger.workspace = true
futures-util = { workspace = true }
glob = "0.3.4"
itertools = { workspace = true }
pglite-oxide = "0.5.1"
rand = { workspace = true }
tempfile = "3.27.0"
uuid = { workspace = true }
