[tool.poetry]
name = "trailbase"
version = "0.7.2"
description = "TrailBase client for Python"
authors = ["TrailBase <contact@trailbase.io>"]
repository = "https://github.com/trailbaseio/trailbase"
homepage = "https://trailbase.io"
license = "Apache-2.0 OR OSL-3.0"
readme = "README.md"
requires-poetry = ">=2.0"

[tool.poetry.dependencies]
python = "^3.13"
httpx = "^0.28.1"
pyjwt = "^2.10.0"
cryptography = "^50.0.0"

[tool.poetry.group.dev.dependencies]
black = "^26.5.1"
mintotp = "^0.3.0"
pyright = "^1.1.408"
pytest = "^9.1.1"
flake8 = "^7.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# NOTE: flake8 linter has to be configured in .flake8
[tool.black]
line-length = 108

[tool.pyright]
venvPath = "."
venv = ".venv"
pythonVersion = "3.12"
pythonPlatform = "All"
typeCheckingMode = "strict"
verboseOutput = true
