[package]
name = "trailbase-cli"
version = "0.2.0"
edition = "2024"
license = "OSL-3.0"
publish = false

[lib]
doctest = false

[[bin]]
name = "trail"

[features]
default = ["trailbase/wasm", "geos", "mcp"]
geos-static = ["trailbase/geos-static"]
geos = ["trailbase/geos"]
mcp = ["dep:rmcp", "dep:rmcp-openapi"]
ws = ["trailbase/ws"]

[dependencies]
axum = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
itertools = { workspace = true }
jsonwebtoken = { workspace = true }
log = { workspace = true }
mimalloc = { version = "^0.1.52", default-features = false }
reqwest = { workspace = true }
rmcp = { version = "^3.1.4", default-features = false, features = ["server", "transport-io"], optional = true }
rmcp-openapi = { workspace = true, optional = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlite-vec = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
trailbase = { workspace = true }
trailbase-build = { workspace = true }
trailbase-client = { workspace = true }
trailbase-extension = { workspace = true }
trailbase-sqlite = { workspace = true }
trailbase-wasm-component-repo = { workspace = true }
trailbase-wasm-runtime-host = { workspace = true }
url = "2.5.8"
utoipa = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
trailbase-build = { workspace = true }
