[package]
name = "trailbase-cli"
version = "0.2.0"
edition = "2024"
license = "OSL-3.0"
publish = false

[lib]
doctest = false

[[bin]]
name = "trail"

[features]
default = ["trailbase/wasm", "trailbase/geos"]
geos-static = ["trailbase/geos-static"]
geos = ["trailbase/geos"]
swagger = ["dep:utoipa-swagger-ui"]
ws = ["trailbase/ws"]

[dependencies]
axum = { version = "^0.8.1", features=["multipart"] }
base64 = { workspace = true }
chrono = "^0.4.38"
clap = { workspace = true }
env_logger = { workspace = true }
itertools = "0.15.0"
jsonwebtoken = { version = "11.0.0", default-features = false, features = ["rust_crypto"] }
log = "^0.4.21"
mimalloc = { version = "^0.1.41", default-features = false }
reqwest = { workspace = true }
rmcp = { version = "^3.1.2", default-features = false, features = ["server", "transport-io"] }
rmcp-openapi = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlite-vec = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
trailbase = { workspace = true }
trailbase-build = { workspace = true }
trailbase-client = { workspace = true }
trailbase-extension = { workspace = true }
trailbase-sqlite = { workspace = true }
trailbase-wasm-component-repo = { workspace = true }
trailbase-wasm-runtime-host = { workspace = true }
url = "2.5.4"
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true, optional = true }
uuid = { workspace = true }

[build-dependencies]
trailbase-build = { workspace = true }
