name: 'Setup Client Environments'
description: 'Sets up the client build/test environment on Ubuntu'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v7
      with:
        python-version: '3.14'
    - name: Install Poetry
      shell: bash
      run: |
        pipx install --python python3.14 "poetry==2.4.1"
        poetry -C client/python config virtualenvs.in-project true

    - uses: actions/cache@v6
      with:
        path: client/python/.venv
        key: poetry-${{ runner.os }}-py3.14-${{ hashFiles('client/python/poetry.lock') }}
        restore-keys: |
          poetry-${{ runner.os }}-py3.14-

    - name: Install Python Dependencies
      shell: bash
      run: poetry -C client/python install

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.47.2
        cache: true

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.x'

    # - name: Setup Go
    #   uses: actions/setup-go@v5
    #   with:
    #     go-version: "1.24.x"
    # Swift 6.1 is preinstalled and swift-action sporadically fails on
    # gpg issues: https://github.com/swift-actions/setup-swift/issues/694
    # - uses: swift-actions/setup-swift@v2
    #   with:
    #     swift-version: "6.1"
