// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Job = { id: number, name: string, schedule: string, enabled: boolean, next: bigint | null, latest: [bigint, string | null] | null, };
