// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogJson } from "./LogJson";
import type { Stats } from "./Stats";

export type ListLogsResponse = { total_row_count: bigint, cursor: string | null, entries: Array<LogJson>, stats: Stats | null, };
