// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";

export type QueryResponse = { columns: Array<Column> | null, rows: Object[][], };
