// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReadFilesRequest = { pk_column: string, 
/**
 * The primary key (of any type since we're in row instead of RecordAPI land) of rows that
 * shall be deleted.
 */
pk_value: Object, file_column_name: string, file_index: number | null, };
