// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnOrder } from "./ColumnOrder";

export type TableIndex = { name: string, table_name: string, columns: Array<ColumnOrder>, unique: boolean, predicate: string | null, };
