// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UniqueConstraint = { name: string | null, 
/**
 * Identifiers of the columns that are unique.
 * TODO: Should be indexed/ordered column.
 */
columns: Array<string>, };
