// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateRowRequest = { primary_key_column: string, primary_key_value: Object, 
/**
 * This is expected to be a map from column name to value.
 *
 * Note that using an array here wouldn't make sense. The map allows for sparseness and only
 * updating specific cells.
 */
row: { [key: string]: Object | undefined }, };
