interface host-endpoint {
  variant tx-error {
    other(string)
  }

  variant value {
    null,
    text(string),
    blob(list<u8>),
    integer(s64),
    real(f64),
  }

  // NOTE: Ideally, we'd use these but they currently block guests.
  execute: func(query: string, params: list<value>) -> result<u64, tx-error>;
  query: func(query: string, params: list<value>) -> result<list<list<value>>, tx-error>;

  // However, transactions have to be sync.
  tx-begin: func() -> result<_, tx-error>;
  tx-commit: func() -> result<_, tx-error>;
  tx-rollback: func() -> result<_, tx-error>;

  tx-execute: func(query: string, params: list<value>) -> result<u64, tx-error>;
  tx-query: func(query: string, params: list<value>) -> result<list<list<value>>, tx-error>;
}
