// TODO: We should probably include the semantic version into the package name
// as it is convention. However, this is a breaking change.
package trailbase:component@0.1.0;
// package trailbase:runtime;

// Note, everything is from the guest's perspective, i.e.:
//  * imports are provided by the host
//  * exports are provided by the guest
//
//  Includes are used to include a world into another world.

@since(version = 0.1.0)
world imports {
  import host-endpoint;
}

// @since(version = 0.1.0)
// world exports {
//   @since(version = 0.1.0)
//   export trailbase:init/init-endpoint@0.1.0;
// }

@since(version = 0.1.0)
world interfaces {
  // Pull in WASIp2 http interface for outbound requests.
  import wasi:http/outgoing-handler@0.2.6;

  // Pull in WASIp2 filesystem interfaces.
  include wasi:filesystem/imports@0.2.6;

  // Pull in WASI random interfaces.
  include wasi:random/imports@0.2.6;

  // Pull in WSAI Key-Value interfaces.
  include wasi:keyvalue/imports@0.2.0-draft;

  // TrailBase's interfaces:
  @since(version = 0.1.0)
  include imports;

  @since(version = 0.1.0)
  include trailbase:init/interfaces@0.1.0;
}
