// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ViewColumn } from "./ViewColumn";

export type ColumnMapping = { columns: Array<ViewColumn>, 
/**
 * Group by that can be used as a key for record APIs.
 */
group_by: number | null, 
/**
 * A list of joins.
 */
joins: Array<number>, };
