// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeleteRowRequest = { primary_key_column: string, 
/**
 * The primary key (of any type since we're in row instead of RecordApi land) of rows that
 * shall be deleted.
 */
value: Object, };
