// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InfoResponse = { version: string, compiler: string | null, commit_hash: string | null, commit_date: string | null, version_tag: string | null, threads: number, };
