// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateUserRequest = { id: string, email: string | null, password: string | null, verified: boolean | null, };
