// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";
import type { QualifiedName } from "./QualifiedName";

export type View = { name: QualifiedName, 
/**
 * Columns may be inferred from a view's query.
 *
 * Views can be defined with arbitrary queries referencing arbitrary sources: tables, views,
 * functions, ..., which makes them inherently not type safe and therefore their columns not
 * well defined.
 *
 * NOTE: Should all this inference be in ViewMetadata?
 */
columns: Array<Column> | null, query: string, temporary: boolean, };
