// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChangeEmailRequest = { csrf_token: string, old_email: string | null, new_email: string, redirect_uri: string | null, };
