// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateUserRequest = { email?: string, username?: string, password: string, 
/**
 * Whether above email should be considers verified.
 */
verified: boolean, admin: boolean, };
