// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HttpMethodType = "Get" | "Post" | "Head" | "Options" | "Patch" | "Delete" | "Put" | "Trace" | "Connect";
