// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitVersion } from "./GitVersion";

export type InfoResponse = { 
/**
 * Build metadata.
 */
compiler: string | null, 
/**
 * Git metadata
 */
commit_hash: string | null, commit_date: string | null, git_version: GitVersion | null, 
/**
 * Runtime metadata.
 */
threads: number, command_line_arguments: Array<string> | null, 
/**
 * Start time in seconds since epoch,
 */
start_time: bigint, 
/**
 * Experimental Postgres mode
 */
postgres: boolean, };
