// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Operation } from "./Operation";

export type TransactionRequest = { operations: Array<Operation>, transaction: boolean | null, };
