// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WasmComponent = { name: string, display_name: string | null, description: string | null, icon: string | null, admin_ui_path: string | null, guest_runtime: string | null, };
