// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WasmComponent = { name: string, path: string, repo_id?: string, installed: boolean, display_name?: string, description?: string, icon?: string, admin_ui_path?: string, guest_runtime?: string, };
