// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WasmComponent = { name: string, path: string, repo_id?: string, 
/**
 * Whether the component is loaded by the server. This is different from `installed`.
 */
loaded: boolean, 
/**
 * Whether the component is present ("installed") in the file-system. There may be skew with
 * loaded, if the component was newly added/removed and a reload hasn't happened yet.
 */
installed: boolean, display_name?: string, description?: string, icon?: string, admin_ui_path?: string, guest_runtime?: string, };
