import { cleanup, fireEvent, render, screen, waitFor } from "@solidjs/testing-library";
import * as Solid from "solid-js";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { LogJson } from "@bindings/LogJson";

const state = vi.hoisted(() => ({
  params: {} as Record<string, string | undefined>, setParams: vi.fn(), version: null as (() => void) | null,
  list: { data: undefined as any, error: undefined as any, loading: false, fetching: false, refetch: vi.fn() },
  stats: { data: undefined as any, error: undefined as any, loading: false, fetching: false, refetch: vi.fn() },
  listOptions: [] as any[], statsOptions: [] as any[], fetchLogs: vi.fn(), fetchStats: vi.fn(), insights: {} as any,
}));
vi.mock("@solidjs/router", () => ({ useSearchParams: () => { const [, bump] = Solid.createSignal(0); state.version = () => bump(n => n + 1); const p = new Proxy(state.params, { get: (_, k: string) => (state.version?.(), state.params[k]) }); state.setParams.mockImplementation((next: any) => { Object.assign(state.params, next); state.version?.(); }); return [p, state.setParams]; } }));
vi.mock("@tanstack/solid-query", () => ({ useQuery: (factory: any) => { const kind = factory().queryKey[0] === "logs" ? "list" : "stats"; const box = state[kind]; const [data, setData] = Solid.createSignal(box.data); const [error, setError] = Solid.createSignal(box.error); const [v, bump] = Solid.createSignal(0); Solid.createEffect(() => { const opts = factory(); (kind === "list" ? state.listOptions : state.statsOptions).push(opts); void opts.queryFn().then((d: any) => { box.data = d; box.error = undefined; setData(d); setError(undefined); bump(n => n + 1); }, (e: any) => { box.error = e; setError(e); bump(n => n + 1); }); }); return { get data() { v(); return data(); }, get error() { v(); return error(); }, get isLoading() { v(); return box.loading; }, get isFetching() { v(); return box.fetching; }, get isRefetching() { v(); return box.fetching; }, refetch: (...a: any[]) => { box.refetch(...a); const opts = kind === "list" ? state.listOptions.at(-1) : state.statsOptions.at(-1); return opts.queryFn().then((d: any) => { box.data = d; setData(d); bump(n => n + 1); }); } }; } }));
vi.mock("@/lib/api/logs", () => ({ fetchLogs: state.fetchLogs, fetchStats: state.fetchStats }));
vi.mock("@/components/logs/LogsInsights", () => ({ LogsInsights: (p: any) => { state.insights = p; return <div data-testid="insights">Insights {p.loading ? "loading" : ""}{p.error ? "error" : ""}<button onClick={p.onRetry}>Retry insights</button></div>; } }));
import LogsPage from "@/components/logs/LogsPage";

const fixture: LogJson = { id: 1n, created: 1700000000, status: 200, method: "GET", url: "/api/items", latency_ms: 12.5, client_ip: "192.0.2.1", client_geoip_cc: "FR", client_geoip_city: { name: "Paris", country_code: "FR" }, referer: "", user_agent: "", user_id: null };
const response = (entries = [fixture], total_row_count: bigint = BigInt(entries.length), cursor?: string) => ({ entries, total_row_count, cursor });
beforeEach(() => { vi.clearAllMocks(); state.params = {}; state.listOptions = []; state.statsOptions = []; state.list.data = response(); state.stats.data = { rates: [], country_codes: null }; state.list.error = state.stats.error = undefined; state.list.loading = state.stats.loading = false; state.list.fetching = state.stats.fetching = false; state.fetchLogs.mockResolvedValue(response()); state.fetchStats.mockResolvedValue({ rates: [], country_codes: null }); });
afterEach(cleanup);
const setup = async () => { render(() => <LogsPage />); await waitFor(() => expect(state.fetchLogs).toHaveBeenCalled()); };

 describe("LogsPage integration", () => {
  it("uses exact independent keys and fetches", async () => { await setup(); expect(state.listOptions[0].queryKey).toEqual(["logs", 20, 0, "", ""]); expect(state.statsOptions[0].queryKey).toEqual(["log-stats", ""]); expect(state.fetchLogs).toHaveBeenCalledWith(20, 0, undefined, undefined, undefined); });
  it("applies, clears, and resubmits filters through both queries", async () => { await setup(); const input = screen.getByRole("textbox", { name: "Filter rows" }); await fireEvent.input(input, { target: { value: "status >= 500" } }); await fireEvent.click(screen.getByRole("button", { name: "Apply filter" })); expect(state.params.filter).toBe("status >= 500"); expect(state.params.pageIndex).toBeUndefined(); await waitFor(() => expect(state.params.filter).toBe("status >= 500")); const a=state.list.refetch.mock.calls.length,b=state.stats.refetch.mock.calls.length; state.setParams({ filter: "status >= 500" }); await fireEvent.input(input, { target: { value: "status >= 500" } }); await fireEvent.click(screen.getByRole("button", { name: "Apply filter" })); expect(state.list.refetch.mock.calls.length).toBeGreaterThanOrEqual(a); expect(state.stats.refetch.mock.calls.length).toBeGreaterThanOrEqual(b); });
  it("renders seven independent headers and row values", async () => { await setup(); expect(screen.getAllByRole("columnheader").map(x=>x.textContent)).toEqual(["Time","Status","Method","Request","Latency","Client","User"]); expect(screen.getByText("/api/items")).toBeInTheDocument(); expect(screen.getByText("12.5 ms")).toBeInTheDocument(); expect(screen.getByText("Paris, FR")).toBeInTheDocument(); expect(screen.getByText("—")).toBeInTheDocument(); expect(screen.getByText("200")).toBeInTheDocument(); });
  it("keeps controls and skeleton while initially loading", async () => { state.list.loading=true; state.stats.loading=true; render(()=><LogsPage/>); expect(screen.getByText("Filter syntax")).toBeInTheDocument(); expect(screen.getByTestId("insights")).toBeInTheDocument(); });
  it("shows empty states and clear filter", async () => { state.fetchLogs.mockResolvedValue(response([],0n)); await setup(); await waitFor(() => expect(screen.getByText("0 requests")).toBeInTheDocument()); const i=screen.getByRole("textbox",{name:"Filter rows"}); state.setParams({ filter: "url ~ '%'" }); await fireEvent.input(i,{target:{value:"url ~ '%'"}}); await waitFor(() => expect(state.params.filter).toBe("url ~ '%'")); expect(state.params.filter).toBe("url ~ '%'"); await fireEvent.click(screen.getByRole("button",{name:"Clear filter"})); expect(screen.getByRole("textbox",{name:"Filter rows"})).toBeInTheDocument(); });
  it("exposes valid filter syntax without contains", async () => { await setup(); expect(screen.getByText("Filter syntax").parentElement?.textContent).toMatch(/status.*method.*latency.*url/s); expect(screen.getByText(/client_ip/)).toBeInTheDocument(); expect(screen.getByText(/user_id/)).toBeInTheDocument(); expect(screen.queryByText(/contains/)).not.toBeInTheDocument(); });
  it("opens the real detail sheet from row and restores focus", async () => { await setup(); await waitFor(() => expect(screen.getAllByRole("row").length).toBeGreaterThan(1)); const row=screen.getAllByRole("row")[1] as HTMLTableRowElement; await fireEvent.click(row); await waitFor(()=>expect(screen.getByText("GET /api/items")).toBeInTheDocument()); await fireEvent.keyDown(document, { key: "Escape" }); await waitFor(()=>expect(document.activeElement).toBe(row)); });
 });
