[package]
name = "trailbase-wasm-runtime-host"
version = "0.1.0"
edition = "2024"
license = "OSL-3.0"
description = "WASM runtime for the TrailBase framework"
homepage = "https://trailbase.io"
exclude = [
  "**/node_modules/",
  "**/dist/",
]

[lib]
doctest = false

[dependencies]
bytes = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlite3-parser = { workspace = true }
thiserror = "2.0.20"
trailbase-schema = { workspace = true }
trailbase-sqlvalue = { workspace = true, features = ["rusqlite"] }
trailbase-sqlite = { workspace = true }
trailbase-wasm-common = { workspace = true }
trailbase-wasi-keyvalue = { workspace = true }
tokio = { workspace = true }
tracing = "0.1.44"
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
wasmtime-wasi-http = { workspace = true }
wasmtime-wasi-io = { workspace = true }
const_format = "0.2.36"
deadpool = { version = "0.13.1", default-features = false, features = ["managed", "rt_tokio_1"] }
