export type * from "@bindings/AlterIndexRequest";
export type * from "@bindings/AlterTableRequest";
export type * from "@bindings/Column";
export type * from "@bindings/ColumnDataType";
export type * from "@bindings/ColumnOption";
export type * from "@bindings/ColumnOrder";
export type * from "@bindings/ConfiguredOAuthProvidersResponse";
export type * from "@bindings/CreateIndexRequest";
export type * from "@bindings/CreateIndexResponse";
export type * from "@bindings/CreateTableRequest";
export type * from "@bindings/CreateTableResponse";
export type * from "@bindings/CreateUserRequest";
export type * from "@bindings/DeleteRowRequest";
export type * from "@bindings/DeleteRowsRequest";
export type * from "@bindings/DropIndexRequest";
export type * from "@bindings/DropTableRequest";
export type * from "@bindings/ForeignKey";
export type * from "@bindings/GeneratedExpressionMode";
export type * from "@bindings/JsonSchema";
export type * from "@bindings/ListJsonSchemasResponse";
export type * from "@bindings/ListLogsResponse";
export type * from "@bindings/ListRowsResponse";
export type * from "@bindings/ListSchemasResponse";
export type * from "@bindings/ListUsersResponse";
export type * from "@bindings/LogJson";
export type * from "@bindings/LoginRequest";
export type * from "@bindings/LoginResponse";
export type * from "@bindings/Mode";
export type * from "@bindings/OAuthProviderEntry";
export type * from "@bindings/OAuthProviderResponse";
export type * from "@bindings/ParseRequest";
export type * from "@bindings/ParseResponse";
export type * from "@bindings/QueryRequest";
export type * from "@bindings/QueryResponse";
export type * from "@bindings/ReadFilesRequest";
export type * from "@bindings/ReferentialAction";
export type * from "@bindings/Stats";
export type * from "@bindings/Table";
export type * from "@bindings/TableIndex";
export type * from "@bindings/TableTrigger";
export type * from "@bindings/View";
export type * from "@bindings/UniqueConstraint";
export type * from "@bindings/UpdateJsonSchemaRequest";
export type * from "@bindings/UpdateRowRequest";
export type * from "@bindings/UpdateUserRequest";
export type * from "@bindings/UserJson";

export type FileUpload = {
  id: string;
  filename: string | undefined;
  content_type: string | undefined;
  mime_type: string | string;
};

export type FileUploads = FileUpload[];
