[package]
name = "trailbase-extension"
version = "0.3.0"
edition = "2024"
license = "OSL-3.0"
description = "SQLite extension used by TrailBase"
homepage = "https://trailbase.io"
repository = "https://github.com/trailbaseio/trailbase"
readme = "../../README.md"

[lib]
crate-type=["rlib"]

[dependencies]
arc-swap = "1.9.2"
argon2 = { workspace = true }
base64 = { workspace = true }
bcrypt = "0.19.3"
jsonschema = { version = "0.53.0", default-features = false }
maxminddb = "0.30.3"
parking_lot = { workspace = true }
quick_cache = { version = "0.7.0", default-features = false }
regex = "1.13.1"
# NOTE: rusqlite must not enable "bundled" for the .so built to work.
rusqlite = { version = "0.40.2", default-features = false, features = ["functions"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = "2.0.20"
uuid = { workspace = true }
validator = { version = "0.21.0", default-features = false }
