// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Table } from "./Table";
import type { TableIndex } from "./TableIndex";
import type { TableTrigger } from "./TableTrigger";
import type { View } from "./View";

export type ListSchemasResponse = { 
/**
 * List of tuples of `Table` schema + `CREATE TABLE` query.
 */
tables: Array<[Table, string]>, 
/**
 * List of tuples of `TableIndex` schema + `CREATE INDEX` query.
 */
indexes: Array<[TableIndex, string]>, 
/**
 * List of tuples of `TableTrigger` schema + `CREATE Trigger` query.
 */
triggers: Array<[TableTrigger, string]>, 
/**
 * List of tuples of `View` schema + `CREATE View` query.
 */
views: Array<[View, string]>, };
