// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QueryRequest = { 
/**
 * The Query to execute. May be multiple statements separated by ";".
 */
query: string, 
/**
 * Databases to attach.
 */
attached_databases: Array<string> | null, 
/**
 * Whether queries altering the schema should be rejected.
 */
allow_schema_alteration: boolean, };
