// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegisterUserRequest = { email: string | null, username: string | null, password: string, password_repeat: string, redirect_uri: string | null, };
