[package]
name = "trailbase-wasm"
version = "0.6.1"
edition = "2024"
license = "OSL-3.0"
description = "WASM runtime for the TrailBase framework"
homepage = "https://trailbase.io"
repository = "https://github.com/trailbaseio/trailbase"
readme = "../../README.md"

[dependencies]
base64 = { workspace = true }
bytes = { version = "1.12.1", default-features = false }
futures-util = { workspace = true }
http = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_path_to_error = "0.1.20"
serde_urlencoded = "0.7.1"
static_assertions = "1.1.0"
thiserror = "2.0.20"
trailbase-sqlvalue = { workspace = true }
trailbase-wasm-common = { workspace = true }
url = "2.5.8"
wit-bindgen = "0.61.1"
wstd = "=0.5.6"
