name: release

on:
  push:
    tags:
      - "v*.*.*"

env:
  TOOLCHAIN_VERSION: 1.98.1
  CARGO_PROFILE_RELEASE_LTO: "fat"
  CARGO_PROFILE_RELEASE_CODEGEN_UNITS: "1"
  PNPM_OFFLINE: "TRUE"
  ARCHIVE_PREFIX: trailbase_${{  github.ref_name }}

permissions:
  contents: read

jobs:
  # NOTE: We use Docker. Otherwise getting compatible versions for
  # musl-gcc, g++ (GEOS is C++) and rustc is borderline impossible.
  release-linux:
    strategy:
      matrix:
        include:
          - ARCH: x86_64
            RUNS_ON: ubuntu-latest
          - ARCH: aarch64
            RUNS_ON: ubuntu-24.04-arm
    runs-on: ${{ matrix.RUNS_ON }}
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
          # No shallow checkout, i.e. fetch all tags (used for versioning the binary).
          fetch-depth: 0
      - name: Inspect Checkout
        run: git describe --tags
      - uses: ./.github/actions/setup_pnpm
      - name: Build a Builder Image
        run: |
          docker build -f Dockerfile.ci \
            --build-arg BASE_IMAGE_TAG=${{ matrix.ARCH }}-musl \
            --build-arg RUST_TARGET=${{ matrix.ARCH }}-unknown-linux-musl \
            --build-arg RUST_TOOLCHAIN_VERSION=${{ env.TOOLCHAIN_VERSION }} \
            -t builder:latest .

      - name: Rust Build using the Builder
        run: |
          env && \
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -e CARGO_PROFILE_RELEASE_LTO=${{ env.CARGO_PROFILE_RELEASE_LTO }} \
            -e CARGO_PROFILE_RELEASE_CODEGEN_UNITS=${{ env.CARGO_PROFILE_RELEASE_CODEGEN_UNITS }} \
            -e PNPM_OFFLINE=FALSE \
            builder:latest \
              sh -c "git describe --tags && /root/.cargo/bin/cargo build --target ${{ matrix.ARCH }}-unknown-linux-musl --release --features=geos-static --bin=trail"

      - name: Check Binary Version
        run: target/${{ matrix.ARCH }}-unknown-linux-musl/release/trail --version
      - name: Package Artifacts
        run: |
          zip -r -j ${{ env.ARCHIVE_PREFIX }}_${{ matrix.ARCH }}_linux.zip \
            target/${{ matrix.ARCH }}-unknown-linux-musl/release/trail CHANGELOG.md LICENSE
      - uses: actions/upload-artifact@v7
        with:
          name: release-linux-${{ matrix.ARCH }}
          path: ${{ env.ARCHIVE_PREFIX }}_${{ matrix.ARCH }}_linux.zip

  release-macos:
    strategy:
      matrix:
        include:
          - ARCH: aarch64
          - ARCH: x86_64
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Inspect Checkout
        run: git describe --tags
      - name: Install Dependencies
        run: brew update && brew install protobuf
      - uses: ./.github/actions/setup_pnpm
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.TOOLCHAIN_VERSION }}
          target: ${{ matrix.ARCH }}-apple-darwin
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: release-macos-${{ matrix.ARCH }}
      - name: Rust Build
        run: |
          env
          cargo build --target ${{ matrix.ARCH }}-apple-darwin --release --features=geos-static --bin=trail

      - name: Check Binary Version
        run: target/${{ matrix.ARCH }}-apple-darwin/release/trail --version
      - name: Package Artifacts
        run: |
          zip -r -j ${{ env.ARCHIVE_PREFIX }}_${{ matrix.ARCH }}_apple_darwin.zip \
            target/${{ matrix.ARCH }}-apple-darwin/release/trail CHANGELOG.md LICENSE
      - uses: actions/upload-artifact@v7
        with:
          name: release-macos-${{ matrix.ARCH }}
          path: ${{ env.ARCHIVE_PREFIX }}_${{ matrix.ARCH }}_apple_darwin.zip

  release-windows:
    runs-on: windows-latest
    env:
      RUST_TARGET: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
          # No shallow checkout, i.e. fetch all tags (used for versioning the binary).
          fetch-depth: 0
      - name: Inspect Checkout
        run: git describe --tags
      - uses: MinoruSekine/setup-scoop@v5.0.1
        with:
          buckets: extras
          apps: nodejs protobuf zip
      - uses: ./.github/actions/setup_pnpm
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.TOOLCHAIN_VERSION }}
          target: ${{ env.RUST_TARGET }}
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: release-windows
      - name: Rust Build
        shell: bash
        run: |
          env
          cargo build --target ${{ env.RUST_TARGET }} --release --features=geos-static --bin=trail

      - name: Check Binary Version
        shell: bash
        run: target/${{ env.RUST_TARGET }}/release/trail.exe --version
      - name: Package Artifacts
        shell: bash
        run: |
          zip -r -j ${{ env.ARCHIVE_PREFIX }}_x86_64_windows.zip \
            target/${{ env.RUST_TARGET }}/release/trail.exe CHANGELOG.md LICENSE
      - uses: actions/upload-artifact@v7
        with:
          name: release-windows-x86_64
          path: ${{ env.ARCHIVE_PREFIX }}_x86_64_windows.zip

  release-wasm-components:
    strategy:
      matrix:
        include:
          - name: auth_ui
            package-name: trailbase-auth-ui-component
          - name: tetris
            package-name: trailbase-tetris-component
    runs-on: ubuntu-latest
    env:
      RUST_TARGET: wasm32-wasip2

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Inspect Checkout
        run: git describe --tags

      - id: release_component
        uses: ./.github/actions/release_component
        with:
          toolchain-version: ${{ env.TOOLCHAIN_VERSION }}
          rust-target: ${{ env.RUST_TARGET }}
          binary-path: target/${{ env.RUST_TARGET }}/release/trailbase_${{ matrix.name }}_component.wasm
          package-name: ${{ matrix.package-name }}
          archive-name: ${{ env.ARCHIVE_PREFIX }}_wasm_${{ matrix.name }}.zip
      - uses: actions/upload-artifact@v7
        with:
          name: release-wasm-${{ matrix.name }}
          path: ${{ env.ARCHIVE_PREFIX }}_wasm_${{ matrix.name }}.zip

  publish-release:
    needs:
      - release-linux
      - release-macos
      - release-windows
      - release-wasm-components
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - name: Get release notes from changelog
        run: |
          export VERSION=$(echo ${{  github.ref_name }} | sed 's/^v//')
          echo "VERSION = ${VERSION}"
          awk "/## v${VERSION}.*/{include=1; next} /## v.*/{include=0} include && NF" CHANGELOG.md > ./CHANGELOG-release.md
          cat ./CHANGELOG-release.md
      - uses: actions/download-artifact@v4
        with:
          pattern: "release-*"
          path: ./release-artifacts
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          body_path: ./CHANGELOG-release.md
          files: ./release-artifacts/*
