name: test

on:
  pull_request:
  push:
    branches:
      - main
      - dev

env:
  TOOLCHAIN_VERSION: 1.98.1

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: all-features
            cargo_args: --all-features
          - name: no-default-features
            cargo_args: --all-targets --no-default-features
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - id: free_disk
        uses: ./.github/actions/free_disk

      - id: setup_build
        uses: ./.github/actions/setup_build
        with:
          cache-key-suffix: build-${{ matrix.name }}
          toolchain-version: ${{ env.TOOLCHAIN_VERSION }}

      - name: "Build with ${{ matrix.cargo_args }}"
        env:
          RUST_BACKTRACE: 1
        run: cargo build ${{ matrix.cargo_args }}

      # Just to monitor the runner's disk consumption.
      - name: Monitor Disk Space (End)
        run: df -h

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
          # No shallow checkout, i.e. fetch all tags (used for versioning the binary).
          fetch-depth: 0

      - uses: MinoruSekine/setup-scoop@v5.0.1
        with:
          buckets: extras
          apps: nodejs protobuf zip
      - uses: ./.github/actions/setup_pnpm
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.TOOLCHAIN_VERSION }}
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: build-windows

      - name: "Build with Release Features"
        env:
          RUST_BACKTRACE: 1
        run: cargo build --features=geos-static --bin=trail

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - id: free_disk
        uses: ./.github/actions/free_disk

      - id: setup_build
        uses: ./.github/actions/setup_build
        with:
          cache-key-suffix: test
          toolchain-version: ${{ env.TOOLCHAIN_VERSION }}

      - id: setup_clients
        uses: ./.github/actions/setup_clients

      - name: "Build & Run Tests"
        uses: j178/prek-action@v3.0.0
        env:
          RUST_BACKTRACE: 1
        with:
          extra-args: "--all-files"

      # Just to monitor the runner's disk consumption.
      - name: Monitor Disk Space (End)
        run: df -h

  test-websocket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - id: free_disk
        uses: ./.github/actions/free_disk

      - id: setup_build
        uses: ./.github/actions/setup_build
        with:
          cache-key-suffix: test-websocket
          toolchain-version: ${{ env.TOOLCHAIN_VERSION }}

      - name: "Test Rust Client"
        env:
          RUST_BACKTRACE: 1
        run: cd crates/client && cargo test --features=ws
      - name: "Test TypeScript Client"
        env:
          USE_WS: 1
        run: cd crates/assets/js/client && pnpm test

      # Just to monitor the runner's disk consumption.
      - name: Monitor Disk Space (End)
        run: df -h

  test-pg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - id: free_disk
        uses: ./.github/actions/free_disk

      - id: setup_build
        uses: ./.github/actions/setup_build
        with:
          cache-key-suffix: test-pg
          toolchain-version: ${{ env.TOOLCHAIN_VERSION }}

      - name: "Build & Run Tests"
        env:
          RUST_BACKTRACE: 1
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          max_attempts: 3
          retry_on: any # options: any, timeout, error
          continue_on_error: false
          command: cargo test --features=geos,otel,pg-test

      # Just to monitor the runner's disk consumption.
      - name: Monitor Disk Space (End)
        run: df -h
